---
# tasks file for db
- name: Change mongo config file
  template:
    src: mongod.conf.j2
    dest: /etc/mongod.conf
    mode: 0644
  notify: restart mongod

- name: Show info abouit the env this host belongs to
  debug:
    msg: "!!!{{ env }}!!!"

