---
# tasks file for app
- name: Add unit file for Puma
  copy:
    src: puma.service
    dest: /etc/systemd/system/puma.service
  notify: reload puma

- name: Add config for DB connection
  template:
    src: db_config.j2
    dest: /home/sofinan/db_config
    owner: sofinan
    group: sofinan

- name: enable puma
  systemd: name=puma enabled=yes

- name: Show info abouit the env this host belongs to
  debug:
    msg: "!!!{{ env }}!!!"
